// <auto-generated />
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210409113432_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccessLayer.Entities.Achievements", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AchievementData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiringHistoriesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("HiringHistoriesId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Employees", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.HiringHistories", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeesId");

                    b.ToTable("HiringHistories");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Achievements", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.HiringHistories", null)
                        .WithMany("Achievements")
                        .HasForeignKey("HiringHistoriesId");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.HiringHistories", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Employees", null)
                        .WithMany("HiringHistories")
                        .HasForeignKey("EmployeesId");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Employees", b =>
                {
                    b.Navigation("HiringHistories");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.HiringHistories", b =>
                {
                    b.Navigation("Achievements");
                });
#pragma warning restore 612, 618
        }
    }
}
